name: datahub-template
description: ''
version: 0.0.1
author: nimbus@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: datahubtemplate
  parentArtefactID: prophecysamples
  buildSystem: wheel
  author: null
  createdAt: '2023-09-20 15:18:13'
pipelines:
  pipelines/tpch_examples:
    name: tpch_examples
    description: ''
    author: nimbus@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-20 15:51:08'
    datasets:
      inputs:
      - datasets/tpch-customer
      - datasets/tpch-nation
      outputs:
      - datasets/country-customer-report
    subgraphs: []
    dependencies: {}
datasets:
  datasets/tpch-customer:
    name: tpch-customer
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-20 15:51:33'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-20 15:51:33'
  datasets/tpch-nation:
    name: tpch-nation
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-20 15:51:47'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-20 15:51:47'
  datasets/country-customer-report:
    name: country-customer-report
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-20 15:52:06'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-20 15:52:06'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.2.0
  gems:
    gems/DatahubTable:
      name: DatahubTable
      category: Source/Target
      subCategory: Database
      description: null
      author: nimbus@prophecy.io
      mode: batch
      files:
      - prophecysamples_datahubtemplate/gems/DatahubTable.py
      createdAt: '2023-09-20 15:50:16'
functions:
  author: null
  createdAt: '2023-09-20 15:18:13'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '34935':
    projectUID: 34935
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wD3Rheoe_team_8768/wD3Rheoe_project_34935.git&subPath=
    version: 0.0.3
    isDefault: false
    author: null
    createdAt: '2023-09-20 15:17:55'
pipelineConfigurations: {}
