name: datahub-template
description: ''
version: 0.0.1
author: nimbus@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: datahubtemplate
  parentArtefactID: prophecysamples
  buildSystem: wheel
  author: null
  createdAt: '2023-09-19 00:34:27'
pipelines:
  pipelines/tpch_examples:
    name: tpch_examples
    description: ''
    author: nimbus@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2023-09-19 00:36:47'
    datasets:
      inputs:
      - datasets/tpch-customer
      - datasets/tpch-nation
      outputs:
      - datasets/country-customer-report
    subgraphs: []
    dependencies: {}
datasets:
  datasets/tpch-customer:
    name: tpch-customer
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-19 00:37:48'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-19 00:37:48'
  datasets/tpch-nation:
    name: tpch-nation
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-19 00:38:03'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-19 00:38:03'
  datasets/country-customer-report:
    name: country-customer-report
    description: ''
    author: nimbus@prophecy.io
    createdAt: '2023-09-19 00:38:36'
    mode: batch
    physicalDatasets:
      db_sql:
        fabricId: 5558
        datasetType: Database
        description: ''
        author: nimbus@prophecy.io
        createdAt: '2023-09-19 00:38:36'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.2.0
  gems:
    gems/DatahubTable:
      name: DatahubTable
      category: Source/Target
      subCategory: Database
      description: null
      author: nimbus@prophecy.io
      mode: batch
      files:
      - prophecysamples_datahubtemplate/gems/DatahubTable.py
      createdAt: '2023-09-19 00:34:27'
functions:
  author: null
  createdAt: '2023-09-19 00:34:27'
  udfs: {}
  udafs: {}
  expressions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies:
  '289':
    projectUID: 289
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/u7TxoglX_team_26/4VDU3KKT_project_289.git&subPath=
    version: 0.0.3
    isDefault: false
    author: null
    createdAt: '2023-09-19 19:06:45'
  '290':
    projectUID: 290
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/u7TxoglX_team_26/4VDU3KKT_project_290.git&subPath=
    version: 0.0.1
    isDefault: true
    author: null
    createdAt: '2023-09-20 05:28:01'
pipelineConfigurations: {}
